version: '3'
services:
  api:
    build: .
    command: python -m pytest -m api
  functional:
    build: .
    command: python -m pytest -m functional
  ui:
    build: .
    command: python -m pytest -m ui
