import sqlite3
import random
import string


def generate_random_customers():
    """
    Generates a random customer profile with a first name, last name, email, and a message.

    Returns:
        tuple: A tuple containing:
            - first_name (str): Randomly generated first name (capitalized).
            - last_name (str): Randomly generated last name (capitalized).
            - email (str): Randomly generated email in the format `first_last@example.com`.
            - message (str): Randomly generated message with a maximum length of 256 characters (capitalized).
    """
    domain = "@example.com"
    name_length = random.randint(5, 10)
    message_length = random.randint(1, 256)

    first_name = ''.join(random.choice(string.ascii_lowercase) for _ in range(name_length))
    last_name = ''.join(random.choice(string.ascii_lowercase) for _ in range(name_length))
    email = first_name + "_" + last_name + domain
    message = ''.join(random.choice(string.printable) for _ in range(message_length))
    return first_name.capitalize(), last_name.capitalize(), email, message.capitalize()


def create_database():
    """
    This function creates an SQLIte database containing 'customers' table with columns:
        - id (int):  Auto-incremented primary key
        - first_name (text): Customer first name
        - last_name (text): Customer last name
        - email (text): Customer email
        - message (text): Randomly generated message associated with the customer.
    """
    db = sqlite3.connect('../customers.db')

    db.execute('''
    CREATE TABLE IF NOT EXISTS customers(
        id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT NOT NULL,
        message TEXT NOT NULL)''')

    db.commit()
    db.close()


def insert_customer(first_name, last_name, email, message):
    """
    This function inserts customer data generated by generate_random_customer() function
    into customer DB created by create_database() function
    """
    db = sqlite3.connect('../customers.db')
    db.execute('''
        INSERT INTO customers (first_name, last_name, email, message)
        VALUES (?,?,?,?)
    ''', (first_name, last_name, email, message))
    db.commit()
    db.close()


def main():
    """
    Main function:
    1. Creates customers.db database
    2. Generates 50 random customers data (first name, last name, email, message)
    3. Inserts generated customer data into created customers database
    """
    create_database()

    for _ in range(50):
        first_name, last_name, email, message = generate_random_customers()
        insert_customer(first_name, last_name, email, message)


if __name__ == "__main__":
    main()
