name: Lint Python Code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt update
        apt upgrade -y
        apt install python 3.12.6
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Flake8
      run: |
        flake8 .
